/**
 * Copies the compiled ABI out of the (gitignored) Hardhat artifact into a committed
 * TypeScript module. The app and the subgraph both need the ABI without needing to
 * compile Solidity first.
 *
 *   npm run sync:abi
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";

const artifact = JSON.parse(
  readFileSync("contracts/artifacts/contracts/WorldWideWC.sol/WorldWideWC.json", "utf8"),
);

writeFileSync(
  "lib/wwwc-abi.ts",
  `// Generated by scripts/sync-abi.ts — do not edit by hand.\n` +
    `export const wwwcAbi = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`,
);

mkdirSync("subgraph/abis", { recursive: true });
writeFileSync("subgraph/abis/WorldWideWC.json", `${JSON.stringify(artifact.abi, null, 2)}\n`);

console.log(`ABI synced: ${artifact.abi.length} entries`);
